name: git-auto-commit

on: push

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use git-auto-commit-action
      id: "auto-commit-action"
      uses: ./

    - name: "outputs"
      run: "echo \"${{ steps.auto-commit-action.outputs.changes_detected }}\""
