name: Integration Tests

on: push

jobs:
  test-commit-works:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Add Files
      run: touch {a,b,c}.txt

    - name: Run git-auto-commit
      id: "auto-commit-action"
      uses: ./
      with:
        branch: ci-test
        commit_message: Message
        checkout_options: -b

    - name: Delete Branch
      run: git push -d origin ci-test
